# Google Cloud Build configuration untuk automated deployment
# File ini akan digunakan oleh Cloud Build untuk build dan deploy aplikasi ke Cloud Run

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/swagsuite:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/swagsuite:latest'
      - '.'
    id: 'build-image'

  # Step 2: Push image ke Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/swagsuite:$COMMIT_SHA'
    id: 'push-image'
    waitFor: ['build-image']

  # Step 3: Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/swagsuite:latest'
    id: 'push-latest'
    waitFor: ['build-image']

  # Step 4: Deploy ke Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'swagsuite'
      - '--image'
      - 'gcr.io/$PROJECT_ID/swagsuite:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast2' # Jakarta region, sesuaikan dengan kebutuhan
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production'
    id: 'deploy-cloud-run'
    waitFor: ['push-image']

# Images yang akan di-push ke registry
images:
  - 'gcr.io/$PROJECT_ID/swagsuite:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/swagsuite:latest'

# Options untuk build
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
# Timeout untuk keseluruhan build process
timeout: 1800s
