CREATE TABLE IF NOT EXISTS "po_confirmations" (
  "id" varchar PRIMARY KEY DEFAULT gen_random_uuid(),
  "order_id" varchar NOT NULL REFERENCES "orders"("id"),
  "document_id" varchar,
  "confirmation_token" varchar(255) NOT NULL UNIQUE,
  "status" varchar(50) NOT NULL DEFAULT 'pending',
  "vendor_email" varchar(255),
  "vendor_name" varchar(255),
  "vendor_id" varchar REFERENCES "suppliers"("id"),
  "po_total" decimal(12, 2),
  "sent_at" timestamp,
  "viewed_at" timestamp,
  "confirmed_at" timestamp,
  "declined_at" timestamp,
  "decline_reason" text,
  "confirmation_notes" text,
  "pdf_path" varchar(500),
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now()
);
