ALTER TABLE orders ADD COLUMN IF NOT EXISTS currency VARCHAR DEFAULT 'USD';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tax_rate DECIMAL(5,2) DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS quote_introduction TEXT;
